server:
  port: 0
  tomcat:
    max-connections: 20000
    threads:
      max: 600
      min-spare: 100

spring:
  application:
    name: product-service
  config:
    import:
      - logging.yml
      - storage-db-core.yml
  web.resources.add-mappings: false

---
spring.config.activate.on-profile: local

server:
  port: 8088
